components {
  id: "object"
  component: "/app/scripts/object.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"1\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/images/images.atlas\"\n"
  "}\n"
  ""
  position {
    x: 3.0
    y: 3.0
  }
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 0.001\n"
  "friction: 0.0\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 2.0\n"
  "      y: -1.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.001038004\n"
  "      w: 0.9999995\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: -2.0\n"
  "      y: -18.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: -0.6966516\n"
  "      w: 0.7174097\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "  }\n"
  "  data: 106.110176\n"
  "  data: 32.839115\n"
  "  data: 10.0\n"
  "  data: 75.574745\n"
  "  data: 20.643753\n"
  "  data: 10.0\n"
  "}\n"
  "linear_damping: 1000000.0\n"
  ""
}
