components {
  id: "object"
  component: "/app/scripts/object.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"20\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/images/images.atlas\"\n"
  "}\n"
  ""
  position {
    x: 3.0
    y: 3.0
  }
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 0.001\n"
  "friction: 0.0\n"
  "restitution: 0.5\n"
  "group: \"default\"\n"
  "mask: \"default\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 1.0\n"
  "      y: -96.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: 0.001038004\n"
  "      w: 0.9999995\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      x: 3.0\n"
  "      y: 20.0\n"
  "    }\n"
  "    rotation {\n"
  "      z: -0.6966516\n"
  "      w: 0.7174097\n"
  "    }\n"
  "    index: 3\n"
  "    count: 3\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      y: 63.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 6\n"
  "    count: 1\n"
  "  }\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      x: 2.0\n"
  "      y: -51.0\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 7\n"
  "    count: 1\n"
  "  }\n"
  "  data: 88.65205\n"
  "  data: 21.990692\n"
  "  data: 10.0\n"
  "  data: 25.037989\n"
  "  data: 94.71516\n"
  "  data: 10.0\n"
  "  data: 69.74829\n"
  "  data: 67.783554\n"
  "}\n"
  "linear_damping: 1000000.0\n"
  ""
}
